### ISSUE TITLE
Add link to repository in JOSS paper and contributing information

### ISSUE THREAD

**Issue by dlebauer** [DidierMurilloF/FielDHub#12]
Per requirements, need to add link to repository in the references section, or add a section such as

```
## Availability and Community Guidelines

The software is available at the Comprehensive R Archive Network CRAN and also at the
GitHub repository https://github.com/DidierMurilloF/FielDHub/. The GitHub repository also contains the source code for this paper.

Users and contributors are welcome to contribute, request features, and report bugs in this GitHub repository.
```

It would also be helpful to have a CONTRIBUTING.md or similar that could be referenced here, and would meet the JOSS requirements https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines. Mozilla provides some ideas https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by DidierMurilloF** [comment]
Dear @dlebauer,

You mean we should add a new section in the paper just like 

## Availability and Community Guidelines

The software is available at the Comprehensive R Archive Network CRAN and also at the
GitHub repository https://github.com/DidierMurilloF/FielDHub/. The GitHub repository also contains the source code for this paper.

Users and contributors are welcome to contribute, request features, and report bugs in this GitHub repository.

We can do that. We just need to confirm that is your request. Thanks

Didier Murillo.

**Comment by DidierMurilloF** [comment]
Dear @dlebauer,

I edited the paper and added a new section `Availability and Community Guidelines.`  Please, let me know if you have any questions. Thank you!

Best,

Didier Murillo.
