### ISSUE TITLE
Suggestions to improve documentation

### ISSUE THREAD

**Issue by dlebauer** [DidierMurilloF/FielDHub#14]
Based on JOSS guidelines https://joss.readthedocs.io/en/latest/review_criteria.html#documentation

- it is not clear where to find documentation
  - as an R user I can find the `help(package = 'FielDHub')` and I see this is great!
  - for the community the README can be substantially improved
    - a lot of the content can come directly from the JOSS paper - including the figures and some additional examples ... or have a section on getting help and running examples using `help()` and `example()` functions
    - link to the pkgdown site
 - use `return` only once per function
 - flesh out `run_app` documentation. This is the key user facing function! What are some options that can be passed as `...`?
 - in both the paper and the docs, it could be more clear that there are a large number of useful standalone functions

**Comment by Prof-ThiagoOliveira** [comment]
@dlebauer fair point. @DidierMurilloF, here is a list of all functions I saw more than one `return`. 

- [ ] fct_RCDB_augmented.R
- [ ] fct_CRD.R
- [ ] fct_RCBD.R
- [ ] fct_alpha_lattice.R
- [ ] fct_diagonal_arrangement.R
- [ ] fct_full_factorial.R
- [ ] fct_incomplete_blocks.R
- [ ] fct_latin_square.R
- [ ] fct_optimized_arrangement.R 
- [ ] fct_full_factorial.R
- [ ] fct_incomplete_blocks.R
- [ ] fct_latin_square.R
- [ ] fct_optimized_arrangement.R
- [ ] fct_partially_replicated.R
- [ ] fct_rectangular_lattice.R
- [ ] fct_row_column.R
- [ ] fct_split_families.R
- [ ] fct_split_plot.R
- [ ] fct_split_split_plot.R
- [ ] fct_square_lattice.R
- [ ] fct_strip_plot.R

**Comment by DidierMurilloF** [comment]
@dlebauer and @Prof-ThiagoOliveira  

I got all the suggestions from you on this issue. I pushed all of the changes. Please, let me know if you have any questions! Please, let me know if we can go ahead and close this issue. Thanks. 

Best,

Didier Murillo.
