### ISSUE TITLE
add contributing.md file

### ISSUE THREAD

**Issue by dlebauer** [DidierMurilloF/FielDHub#15]
Per JOSS criteria:

> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

see also: https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by DidierMurilloF** [comment]
@dlebauer thank you for the suggestion. I already added the `contributing.md` file. I am going to push the changes at the end of the day. 

Best,

Didier Murillo

**Comment by DidierMurilloF** [comment]
Dear @dlebauer. I already added the `contributing.md`  file and I pushed all of the changes. Please, let me know if you have any questions!

Best,

Didier Murillo.

**Comment by dlebauer** [comment]
looks great!
