### ISSUE TITLE
Summary and print functions

### ISSUE THREAD

**Issue by Prof-ThiagoOliveira** [DidierMurilloF/FielDHub#4]
Hi, 

I noticed that there are no print and summary functions for each function proposed in the package. I have felt the need for print and summary functions because when, for example, we increase the number of treatments, locations and so on, and print the object, a list of two objects is automatically printed, which sometimes ends up polluting the R output, mainly, due to the "fieldBook" object in that list. 

In this sense, I have worked on the following possible suggestions for you:

```
##' @rdname print.CRD
##' @method print CRD
##' @title Print an \code{CRD} object
##' @usage \method{print}{CRD}(x, ...)
##' @aliases print.CRD
##' @description Prints information about randomization of Completely
##'   Randomized Design (CDR)
##' @return an object inheriting from class \code{CRD}
##' @param x an object inheriting from class
##'   \code{\link[FielDHub]{CRD}}
##'
##' @param ... not used

print.CRD <- function(x, ...){
  cat("Completely Randomized Design (CRD)", "\n\n")
  cat("  Information on the design parameters:", "\n")
  str(x$infoDesign)

  cat("\n", " Head of the data frame with the CRD field book:","\n")
  head(x$fieldBook)
}


##' @rdname summary.CRD
##' @method summary CRD
##' @title Summary an \code{CRD} object
##' @usage \method{summary}{CRD}(object, ...)
##' @aliases summary.CRD
##' @description Summarise information on the design parameters and data frame structure
##' @return an object inheriting from class \code{summary.CRD}
##' @param object an object inheriting from class
##'   \code{\link[FielDHub]{CRD}}
##'
##' @param ... not used

summary.CRD <- function(object, ...) {
  structure(object, oClass=class(object),
            class = "summary.CRD")
}

##' @rdname print.summary.CRD
##' @method summary CRD
##' @title Print the summary of an \code{CRD} object
##' @usage \method{print}{summary.CRD}(object, ...)
##' @aliases print summary.CRD
##' @description Print summary information on the design parameters and data frame structure
##' @return an object inheriting from class \code{CRD}
##' @param object an object inheriting from class
##'   \code{\link[FielDHub]{CRD}}
##'
##' @param ... not used

print.summary.CRD <- function(x, ...){
  cat("Information on the design parameters:", "\n")
  str(x$infoDesign)  
  cat("\n", "Data frame structure with the CRD field book:","\n")
  str(x$fieldBook)
}
```

See the new output example below:
```
crd1 <- CRD(t = 3, 
            reps = 5, 
            plotNumber = 101, 
            seed = 1987, 
            locationName = "Fargo")
```
* Print output:

```
print(crd1)

Completely Randomized Design (CRD) 

  Information on the design parameters: 
List of 5
 $ numberofTreatments: num 3
 $ treatments        : chr [1:3] "T1" "T2" "T3"
 $ Reps              : num 5
 $ locationName      : chr "Fargo"
 $ seed              : num 1987

Data frame head with the CRD field book: 
  ID LOCATION PLOT REP TREATMENT
1  1    Fargo  101   3        T2
2  2    Fargo  102   1        T1
3  3    Fargo  103   1        T2
4  4    Fargo  104   3        T3
5  5    Fargo  105   2        T3
6  6    Fargo  106   3        T1
```

* Summary output

```
s1 <- summary.CRD(object)
s1

Information on the design parameters: 
List of 5
 $ numberofTreatments: num 3
 $ treatments        : chr [1:3] "T1" "T2" "T3"
 $ Reps              : num 5
 $ locationName      : chr "Fargo"
 $ seed              : num 1987

 Data frame structure with the CRD field book: 
'data.frame':	15 obs. of  5 variables:
 $ ID       : int  1 2 3 4 5 6 7 8 9 10 ...
 $ LOCATION : Factor w/ 1 level "Fargo": 1 1 1 1 1 1 1 1 1 1 ...
 $ PLOT     : int  101 102 103 104 105 106 107 108 109 110 ...
 $ REP      : int  3 4 1 3 4 1 1 4 5 2 ...
 $ TREATMENT: Factor w/ 3 levels "T1","T2","T3": 2 2 2 1 1 1 3 3 1 3 ...
```

I would suggest the authors consider both print and summary functions for each function related to experimental design. Clearly, feel free to modify my first suggestion, you also can add some more parameters in each function, e.g.:
```
print.CRD <- function(x, n=10,...){
  cat("Completely Randomized Design (CRD)", "\n\n")
  cat("  Information on the design parameters:", "\n")
  str(x$infoDesign)
  
  cat("\n", "Data frame head with the CRD field book:","\n")
  head(x$fieldBook, n=(min(n, nrow(x$fieldBook))))
}
```
Another alternative could be to include only a print function with the output of the summary function. Just think about it. The optimal idea is to have both functions with non overlapped outputs.

**Comment by Prof-ThiagoOliveira** [comment]
I'm working on that for now, and I'll create a Pull Request when I've finished.

**Comment by DidierMurilloF** [comment]
Thanks for contributing. Thiago, do you suggest this for all functions? I can work at the same time in other functions different from that you are working. Thanks

**Comment by Prof-ThiagoOliveira** [comment]
Yes, I think it will be useful for end-users to have print and summary options for all functions. Clearly, each one's utility may vary from function to function as sometimes a summary has the same information as a print.

**Comment by Prof-ThiagoOliveira** [comment]
Please, note in the pull request I sent you, some changes in the main function were added (I added a class). I think will be good to add this part to all other functions as well.

**Comment by DidierMurilloF** [comment]
Thanks for the nice work on the CRD function. I accepted the pull. I will use those ideas for implementing your suggestions  in all of rest main functions.

**Comment by Prof-ThiagoOliveira** [comment]
@DidierMurilloF How are you doing with this issue? Please, if you have any questions about our discussion here, let me know. I've seen you have made several improvements in all functions. Great job!

**Comment by DidierMurilloF** [comment]
Dear Thiago, thank you for asking. 

Just now I completed this issue. I adapted for each function proposed in the package the summary and print functions that you wrote. Now the end-user can call print and summary to all functions in FielDHub. Thank you so much for your contributions in all of this process. I pushed those changes.  Please, let me know if you have any questions about it. 

Since we finished all suggestions and changes proposed in FieDHub, we are looking forward to receiving any inquiries in the process to get FielDHub in JOSS. Thank you!

Best,

Didier Murillo

**Comment by Prof-ThiagoOliveira** [comment]
Thanks, @DidierMurilloF. You are making excellent work/improvement in the package.
