### ISSUE TITLE
save desplot resulting from `plot()` into object 

### ISSUE THREAD

**Issue by SchmidtPaul** [DidierMurilloF/FielDHub#40]
Hey, I want to make use of your `plot()` function (instead of manually creating my own desplots) for teaching purposes (see [here](https://schmidtpaul.github.io/dsfair_quarto/ch/summaryarticles/designingexperiments.html#crd)) , but I would like to use other colors/layout. I thought I could simply create the resulting plot into an object and alter it afterwards, but the function isnt acutally returning the plot, right? It's just showing it:

``` r
library(FielDHub)

x <- CRD(
  t = letters[1:3],
  reps = 3,
  seed = 42
)

y <- plot(x)
```

![](https://i.imgur.com/vDBo2Mk.png)

``` r
str(y)
#> List of 1
#>  $ field_book:'data.frame':  9 obs. of  7 variables:
#>   ..$ ID       : int [1:9] 1 2 3 4 5 6 7 8 9
#>   ..$ LOCATION : num [1:9] 1 1 1 1 1 1 1 1 1
#>   ..$ PLOT     : int [1:9] 101 102 103 104 105 106 107 108 109
#>   ..$ ROW      : int [1:9] 1 1 1 2 2 2 3 3 3
#>   ..$ COLUMN   : int [1:9] 1 2 3 3 2 1 1 2 3
#>   ..$ REP      : Factor w/ 3 levels "1","2","3": 1 2 2 3 2 3 1 1 3
#>   ..$ TREATMENT: chr [1:9] "a" "b" "b" "c" ...
```

I guess I would only want something like this instead. And as you may know, updating such a plot would be quite simple:

``` r
z <- desplot::desplot(
  data = y$field_book,
  form = TREATMENT ~ ROW + COLUMN,
  text = TREATMENT,
  col.regions = c("#00923f", "#bce2cc", "#e9ecef"),
  cex = 1,
  show.key = FALSE,
  main = NULL
)

z
```

![](https://i.imgur.com/007351G.png)

``` r

update(z, col.regions = c("red", "blue", "green"))
```

![](https://i.imgur.com/b8EOl0O.png)

<sup>Created on 2023-11-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DidierMurilloF** [comment]
Hey, @SchmidtPaul, I think that will be such a nice feature. I am going to add that and deploy it to CRAN in the following weeks. Thank you.

**Comment by SchmidtPaul** [comment]
Hey, just a little reminder that I am still very interested in this. But of course, I understand if you have other priorities.

**Comment by DidierMurilloF** [comment]
FielDHub now returns the plot using the method plot(). This plot object is a ggplot2 object, so we can modify it as any other ggplot2 figure. 

```
library(FielDHub)
library(ggplot2)
```

The same example you shared,

```
x <- CRD(
  t = letters[1:3],
  reps = 3,
  seed = 42
)

y <- plot(x)

p <- y$p
p
```

![](https://raw.githubusercontent.com/DidierMurilloF/unsplash-img/master/img/crd1.png)

```
crd_layout <- y$p +
  ggtitle("FielDHub is great") +
  scale_fill_manual(values = c("red", "blue", "green"))

crd_layout
```

![](https://raw.githubusercontent.com/DidierMurilloF/unsplash-img/master/img/crd2.png)


### Let us try an RCBD,

```
v <- RCBD(
  t = letters[1:6],
  reps = 3,
  seed = 42
)

w <- plot(v)
p <- w$p
p
```

![](https://raw.githubusercontent.com/DidierMurilloF/unsplash-img/master/img/rcbd0.png)

```
rcbd_layout <- w$p +
  ggtitle("RCBD in FielDHub") +
  scale_fill_manual(values = c("red", "blue", "green", "yellow", "purple", "orange"))

rcbd_layout
```

![](https://raw.githubusercontent.com/DidierMurilloF/unsplash-img/master/img/rcbd1.png)

Let's add more features to the plot,

```
rcbd_layout <- rcbd_layout +
  scale_y_continuous(breaks = function(limits) seq(floor(limits[1]), ceiling(limits[2]), by = 1)) +
  scale_x_continuous(breaks = function(limits) seq(floor(limits[1]), ceiling(limits[2]), by = 1)) +
  theme_minimal() + 
  guides(color = "none") +
  theme(plot.background = element_rect(fill = "lightgray"),
        text = element_text(size = 12),
        plot.title = element_text(face = "bold"))
rcbd_layout
```

![](https://raw.githubusercontent.com/DidierMurilloF/unsplash-img/master/img/rcbd2.png)

I think this way of modifying or customizing the plots is acceptable. What do you think? You can test this version using the GitHub version. I am planning to release a new version of the app this weekend.

**Comment by SchmidtPaul** [comment]
Fantastic! Thanks a lot! I immediately applied it to my website - check out the first few examples [here](https://schmidtpaul.github.io/dsfair_quarto/ch/summaryarticles/designingexperiments.html#crd).

I am closing this issue now because it has been solved.

One final note, though. I am assuming you switched from `desplot::desplot()` to `desplot::ggdesplot()`. While this should generally not be a problem and instead be advantageous since ggplot is better in several aspects, note that `desplot::ggdesplot()` is not as complete as `desplot::desplot()` as you can e.g. see in [this](https://github.com/kwstat/desplot/issues/2) or [this](https://github.com/kwstat/desplot/issues/5) issue. Again, it shouldn't actually cause any problems except in special situations but I am just pointing it out.
Finally, though, I have not tested it but suspect it would not be as easy to change the colors of the yellow and black lines generated by `out1=` and `out2=` right? At least I don't know how to change the static color of an existing layer.
