### ISSUE TITLE
Authorship by function

### ISSUE THREAD

**Issue by Prof-ThiagoOliveira** [DidierMurilloF/FielDHub#7]
Dear authors, 

Could you provide authorship for each function in the package rather than just in the description file? This is an important step to see how authors/contributors have contributed to this package's development. Please, remember that each contributor should appear in the description file. Sorry to be a little bit pedantic about it, but you will see this step is important over the next releases (years). When you describe contributors and authors only on the description file, I assumed they have contributed to all functions, which, probably, is not true.

Please, check the box when you have attributed authorship for the following functions:

- [ ] `get_golem_config()`
- [x] `app_server()`
- [x] `app_ui() `
- [x] `alpha_lattice()`
- [x] `CDR()`
- [x] `diagonal_arrangement()`
- [x] `full_factorial()`
- [x] `incomplete_blocks()`
- [x] `latin_square()`
- [x] `optimized_arrangement()`
- [x] `partially_replicated()`
- [x] `RCBD()`
- [x] `RCBD_augmented()`
- [x] `rectangular_lattice()`
- [x] `row_column()`
- [x] `split_families()`
- [x] `split_plot()`
- [x] `split_split_plot()`
- [x] `square_lattice()`
- [x] `strip_plot()`

Thanks.

**Comment by Prof-ThiagoOliveira** [comment]
Please, check the box when you have attributed authorship for the following functions:

- [ ] `get_golem_config()`
- [ ] ` `
- [ ] ` `
- [ ] ` `
- [ ] ` `
- [ ] ` `

**Comment by Prof-ThiagoOliveira** [comment]
Please, check the box when you have attributed authorship for the following functions:

- [ ] `get_golem_config()`
- [ ] `app_server()`
- [ ] `app_ui() `
- [ ] `alpha_lattice()`
- [ ] `CDR()`
- [ ] `diagonal_arrangement()`
- [ ] `full_factorial()`
- [ ] `incomplete_blocks()`
- [ ] `latin_square()`
- [ ] `optimized_arrangement()`
- [ ] `partially_replicated()`
- [ ] `RCBD()`
- [ ] `RCBD_augmented()`
- [ ] `rectangular_lattice()`
- [ ] `row_column()`
- [ ] `split_families()`
- [ ] `split_plot()`
- [ ] `split_split_plot()`
- [ ] `square_lattice()`
- [ ] `strip_plot()`

**Comment by tatirri** [comment]
Dear Professor Thiago Oliveira,
Thank you very much for reaching out to us regarding the authorship of these functions. The two main authors who wrote all these functions are Didier Murillo-Florez and Salvador Alejandro Gezan. We will take into account your recommendations and put their names in the formulas above. The other people included in the paper have contributed with ideas, patches, shiny development coding and field design theory and background related to agriculture/biology applications of the design of experiments.

Thanks for your time and all your contributions to this application and to the paper. 

Have a wonderful rest of your day,

Ana Maria Heilman-Morales

**Comment by Prof-ThiagoOliveira** [comment]
Dear Ana Maria, 

Thank you for your reply. Please note that people who contributed with some idea to the code should also be included as contributors to that function. So, you can distinguish them by attributing to each person a label such as `[aut]` for author or `[ctb]` for a contributor.  

Have a  wonderful rest of your day too!

**Comment by DidierMurilloF** [comment]
Dear Thiago,

I would like to ask you if this is the right way to implement your request. The following information will be in the  R functions description. 

#' @author Didier Murillo [aut],
#'         Salvador Gezan [aut],
#'         Ana Heilman [ctb],
#'         Thomas Walk [ctb], 
#'         Johan Aparicio [ctb], 
#'         Richard Horsley [ctb]

Thank you!

**Comment by Prof-ThiagoOliveira** [comment]
Dear @DidierMurilloF, 

Of course, you can differentiate types of contribution by function; however, it can be too informative. My suggestion here is to include names and email only. These are the most common ways I have been seen in R:

1. Example 1:
#' @author Didier Murillo, \email{your email}, Salvador Gezan, Ana Heilman, ...

2. Example 2:
#' @author Didier Murillo, \email{your email}, Salvador Gezan \email{email}, Ana Heilman \email{email}, ...

Perhaps, my suggestion above may have confounded you. Sorry about that.

**Comment by DidierMurilloF** [comment]
Dear Profesor Thiago,

I added the information for the authorship by function. Please, could you check it? Thank you!

Didier Murillo.

**Comment by Prof-ThiagoOliveira** [comment]
Done!
